### ISSUE TITLE
Mobius, MySQL 충돌 문제

### ISSUE THREAD

**Issue by lsh940131** [IoTKETI/Mobius#15]
2.2.5를 테스트하다 직접 MySQL을 실행해 row를 지웠거든요.

그래서 실제로 DB에 없지만 Mobius에선 POSTMAN에 의해 만들어진 AE 목록은 갖고 있어서

충돌이 나는 것 같은데, 해결 방법 좀 알려주실 수 있으신가요?

**Comment by IoTKETI** [comment]
2가지 방법이 있습니다.
1. lookup 테이블에서 해당 AE를 지우시면 될 것입니다.
2. postman에서 해당 AE를 지우는 요청을 하시면 됩니다.

이미 ae 테이블에서 해당 AE를 지우셨기 때문에 1번으로 하시면 될 것 같습니다.

**Comment by lsh940131** [comment]
감사합니다.
 
lookup을 잊고 있었습니다 ^^;
 
-----Original Message-----
