### ISSUE TITLE
Release number going back from 2.3.4 to 2.0.0

### ISSUE THREAD

**Issue by beaver71** [IoTKETI/Mobius#3]
Just a little note: your previous release was Mobius Yellow Turtle v2.3.8, now you numbered the current release 2.0.0. It seems so strange to go back with number versions.

**Comment by IoTKETI** [comment]
version name is changed. previous version name is Mobius Yellow turtle, current version name is Mobius just.
version number is 2.0 which matched for oneM2M release 2
